spring:
  datasource:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    name: "name"
    password:
    username: sa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true